[9.0][ADD] improve accounting
coopiteasy/addons pull request #132
Opened 2020-11-02 15:34 UTC by mclaeysb

[Task](https://gestion.coopiteasy.be/web?token=R0Qs92cjQIn6BsLb5XTZ&db=coopiteasy#id=5208&view_type=form&model=project.task&action=479)

- Make Payments view accessible for Billing group
- Add filter to payments view on 'today'
- Add filter in payments view on locations (and therefore add locations to payments as related field)

2020-11-04 14:26 UTC, vvrossem requested changes
Nicely done! Unsure about the field `testing` declared in `account.payment`

2020-11-04 14:26 UTC, vvrossem commented on provelo_analytic_account/models/account_payment.py
> +    testing = fields.Text(string="Testfield")
what is the purpose of this field?

2020-11-05 09:41 UTC, robinkeunen requested changes
I think all of this should go under `provelo_customization` module. `provelo_analytic_account` deals with AA customization to talk with BOB.

2020-11-09 16:27 UTC, mclaeysb commented on provelo_analytic_account/models/account_payment.py
> +    testing = fields.Text(string="Testfield")
Oepsie. Well-spotted! Thanks 👍

2020-11-09 16:32 UTC, mclaeysb commented
> I think all of this should go under `provelo_customization` module. `provelo_analytic_account` deals with AA customization to talk with BOB.

@vvrossem your opinion? My reasoning was 'I'm adding a field to an analytic model so it should go in `provelo_analytic_account` - e.g. in case it's needed there later. But I'm happy to move it if you want to keep `provelo_analytic_account` tidy.

2020-11-10 09:29 UTC, robinkeunen commented
> > I think all of this should go under `provelo_customization` module. `provelo_analytic_account` deals with AA customization to talk with BOB.
> 
> @vvrossem your opinion? My reasoning was 'I'm adding a field to an analytic model so it should go in `provelo_analytic_account` - e.g. in case it's needed there later. But I'm happy to move it if you want to keep `provelo_analytic_account` tidy.

Yes, I insist.`provelo_analytic_account` is not about UX customizations related to AA, it's accounting logic specific to the BOB interconnection. I'd much rather keep that separated. Sorry, strong opinion on that one :-)

2020-11-10 09:38 UTC, vvrossem commented
I'd have done the same "mistake", but let's follow `provelo_analytic_account` module's author recommendation and move the code in `provelo_customization`

2020-11-18 13:50 UTC, merged