[11.0] mark invoice as paid by transactions
coopiteasy/addons pull request #158
Opened 2021-02-25 09:44 UTC by robinkeunen

[task](https://gestion.coopiteasy.be/web?#id=6045&view_type=form&model=project.task&action=475&active_id=165)

2021-03-01 11:00 UTC, vvrossem requested changes
I guess you don't override `_get_payment_vals` anymore. 
Some template to remove

2021-03-01 11:00 UTC, vvrossem commented on account_invoice_paid_transaction/demo/model_name_demo.xml
> +    <!-- My demo record data -->
WIP ?

2021-03-01 11:00 UTC, vvrossem commented on account_invoice_paid_transaction/readme/DESCRIPTION.rst
> +Mark invoice as paid if an done transactions exists for the origin sale order.
typo `any`

2021-03-01 11:00 UTC, vvrossem commented on account_invoice_paid_transaction/views/report_name.xml
> +</odoo>
to delete?

2021-03-04 17:34 UTC, robinkeunen commented
Indeed, I finally decided to separate the treatment of sale order related transactions from invoice related transactions. Thanks for the review and sorry for the dirty work I left behind :-)

2021-03-08 09:12 UTC, vvrossem approved these changes
LGTM

2021-03-08 15:49 UTC, merged