[ADD] module checks the structured com of a supplier invoice
coopiteasy/addons pull request #159
Opened 2021-03-02 10:48 UTC by houssine78

allows to check structured communication of a supplier invoice when the company is configured to generated bba com

2021-03-04 09:25 UTC, vvrossem requested changes
LGTM.
Does it replace PR https://github.com/coopiteasy/cie-imported-modules/pull/3/ ?
Could you also add `readme` directory and `.rst` ?

2021-03-04 09:25 UTC, vvrossem commented on account_invoice_check_bba_com/views/account_invoice.xml
> +</odoo>
missing EOL

2021-03-04 09:40 UTC, houssine78 commented
> 
> 
> LGTM.
> Does it replace PR [coopiteasy/cie-imported-modules#3](https://github.com/coopiteasy/cie-imported-modules/pull/3) ?
> Could you also add `readme` directory and `.rst` ?

yes it replaces indead those modules. I'll do it

2021-03-05 14:16 UTC, houssine78 commented
@vvrossem readme directory and .rst files was already there. Did you was asking for something particular ?

2021-03-08 08:40 UTC, vvrossem approved these changes

2021-04-12 07:23 UTC, merged