[FIX] look like customer field has been named "client" in the pos client
coopiteasy/addons pull request #17
Opened 2019-05-13 09:22 UTC by houssine78

2019-08-06 14:54 UTC, houssine78 commented
@robinkeunen @remytms old PR here. I don't remember for which customer is related but it would be great if you could have a look

2019-08-06 15:04 UTC, robinkeunen requested changes
I think you need to fix the previous if-statement :-)

2019-08-06 15:04 UTC, robinkeunen commented on pos_custom_receipt/static/src/xml/pos.xml
>          	 <t t-if='receipt.partner'>
You probably need to dix this line too

2019-08-07 12:59 UTC, houssine78 commented on pos_custom_receipt/static/src/xml/pos.xml
>          	 <t t-if='receipt.partner'>
done !

2019-08-07 13:00 UTC, robinkeunen approved these changes

2019-08-07 19:40 UTC, merged