[WIP][12.0][MIG] sale_order_for_approval
coopiteasy/addons pull request #198
Opened 2022-01-10 09:57 UTC by carmenbianca

Task: https://gestion.coopiteasy.be/web#id=7882&view_type=form&model=project.task&action=475&active_id=210

Not sure how to find report_saleorder_document through the GUI; will have to test later.

2022-01-12 11:28 UTC, carmenbianca commented
Tested; works.

2022-01-12 13:13 UTC, huguesdk requested changes
except those slight changes is the manifest, lgtm. 👍

2022-01-12 13:13 UTC, huguesdk commented on sale_order_for_approval/__manifest__.py
> +    "sequence": 95,
i don’t think this is useful anymore, but i might be mistaken.

2022-01-12 13:13 UTC, huguesdk commented on sale_order_for_approval/__manifest__.py
> +    "installable": True,
true by default, should be removed.

2022-01-13 11:14 UTC, robinkeunen approved these changes

2022-01-13 11:15 UTC, robinkeunen commented
To find `report_saleorder_document` in the UI, you need to find the menuitem calling to the report action and follow its parents hierarchy.

2022-01-19 08:15 UTC, merged