[IMP] O21 add "Print Last Quotation" button on activity
coopiteasy/addons pull request #21
Opened 2019-05-28 13:53 UTC by PierrickBrun

2019-06-13 14:49 UTC, robinkeunen approved these changes
Un commentaire de style/gout pour la sélection du dernier sale.order*. Mais sinon c'est cool 👍 

\* J'ai une aversion héréditaire pour les boucles

2019-06-13 14:49 UTC, robinkeunen commented on resource_activity/models/resource_activity.py
> +            if not sale_order or so.create_date > sale_order.create_date:
Perso, je trierais `self.sale_orders` par `create_date` et de prendre le dernier :-)

2019-08-06 14:56 UTC, houssine78 commented
@robinkeunen any decision about this PR ?

2019-08-06 15:01 UTC, robinkeunen commented
Yep, @PierrickBrun pourra merger à son retour.

2019-08-07 08:15 UTC, robinkeunen requested changes
Il me semble que ce bouton `print last quotation` devrait être accessible depuis les états sale et done. cf tâche https://gestion.coopiteasy.be/web#id=1336&view_type=form&model=project.task

2019-08-07 08:15 UTC, robinkeunen commented on resource_activity/views/resource_activity_views.xml
> +                        <button name="print_last_sale_order" string="Print Last Quotation" type="object" states="quotation"/>
Il me semble que ce bouton devrait être accessible depuis les états `sale` et `done`. cf tâche https://gestion.coopiteasy.be/web#id=1336&view_type=form&model=project.task

2020-01-07 17:17 UTC, robinkeunen commented
closed in favor of https://github.com/coopiteasy/addons/pull/54

2020-01-07 17:17 UTC, closed without merging