12.0 remove website dependency for recaptcha
coopiteasy/addons pull request #218
Opened 2022-03-24 16:03 UTC by victor-champonnois

related to [this issue](https://github.com/coopiteasy/vertical-cooperative/issues/214)
[related pr](https://github.com/coopiteasy/addons/pull/218)

2022-03-28 14:52 UTC, victor-champonnois commented
@robinkeunen @remytms Ready to review !

2022-03-29 09:38 UTC, robinkeunen requested changes

2022-03-29 09:38 UTC, robinkeunen commented on website_recaptcha/models/portal_mixin.py
> +    # recaptcha_key_secret = fields.Char()
delete comments.

2022-03-29 09:38 UTC, robinkeunen commented on website_recaptcha/models/res_config.py
>          self.has_google_recaptcha = bool(self.recaptcha_key_site)
Is this really necessary ? Are the fields `recaptcha_key_site` and `recaptcha_key_secret` not enough ?

2022-03-29 09:38 UTC, robinkeunen commented on website_recaptcha/views/res_config.xml
> +                        groups="group_cooperative_admin"
remove comments

2022-03-29 09:38 UTC, robinkeunen commented on website_recaptcha/views/res_config.xml
> +                            <!-- <label for="has_google_recaptcha" string="reCaptcha" />
same

2022-03-29 14:07 UTC, victor-champonnois commented on website_recaptcha/models/res_config.py
>          self.has_google_recaptcha = bool(self.recaptcha_key_site)
Yes I wasn't sure whether it is worth keeping that. I removed it.

2022-04-14 08:39 UTC, closed without merging