[16.0][ADD] partner_contact_tag
coopiteasy/addons pull request #281
Opened 2023-03-09 15:20 UTC by carmenbianca

## Description

## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#id=10179&action=479&model=project.task&view_type=form&menu_id=536

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

2023-03-10 08:22 UTC, victor-champonnois commented
Sorry I told you it was categ_id but it's actually category_id. You should also add a widget_many2many, like here https://github.com/odoo/odoo/blob/e3a2cf7e77b844b6d0ac375a4fe224f05227fa32/odoo/addons/base/views/res_partner_views.xml#L228

2023-03-10 08:46 UTC, carmenbianca commented
Good catch @victor-champonnois on the widget. It looks much nicer now. :rocket:

2023-03-10 09:34 UTC, victor-champonnois commented
@carmenbianca could you ping me when it's redeployed in test ?

2023-03-10 10:57 UTC, huguesdk requested changes
i think that this module could be useful for others and should be proposed to [OCA/partner-contact](https://github.com/OCA/partner-contact).

the module name should say that this is a view change only. the first impression for me was that it was adding the concept of partner tags (model and all).

2023-03-10 10:57 UTC, huguesdk commented on partner_contact_tag/__manifest__.py
> +    "qweb": [],
```suggestion
    "depends": [
        "base",
    ],
    "data": [
        "views/res_partner_views.xml",
    ],
```
please [avoid empty keys](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#id6).

2023-03-10 10:57 UTC, huguesdk commented on partner_contact_tag/__manifest__.py
> +    "category": "Uncategorized",
most modules in [OCA/partner-contact](https://github.com/OCA/partner-contact) seems to use the "Customer Relationship Management" category.

2023-03-10 10:57 UTC, huguesdk commented on partner_contact_tag/__manifest__.py
> +        Display tag in the pop-up form view when adding a contact to a partner.""",
```suggestion
        Display tags in the pop-up form view when adding a contact to a partner""",
```

2023-03-10 10:57 UTC, huguesdk commented on partner_contact_tag/readme/DESCRIPTION.rst
> +Display tag in the pop-up form view when adding a contact to a partner.
```suggestion
Display tags in the pop-up form view when adding a contact to a partner.
```

2023-03-10 10:57 UTC, huguesdk commented on partner_contact_tag/views/res_partner_views.xml
> +                expr="//notebook/page/field[@name='child_ids']/form/sheet//field[@name='mobile']"
why not put it at the same place as on the regular form?

2023-03-10 10:59 UTC, victor-champonnois commented on partner_contact_tag/views/res_partner_views.xml
> +                expr="//notebook/page/field[@name='child_ids']/form/sheet//field[@name='mobile']"
It's already in the regular form, but not on the popup form

2023-03-10 11:00 UTC, victor-champonnois commented on partner_contact_tag/views/res_partner_views.xml
> +                expr="//notebook/page/field[@name='child_ids']/form/sheet//field[@name='mobile']"
That's why it's a small change, so it's not obvious it has enough value to be proposed  to OCA

2023-03-10 14:06 UTC, huguesdk commented on partner_contact_tag/views/res_partner_views.xml
> +                expr="//notebook/page/field[@name='child_ids']/form/sheet//field[@name='mobile']"
> why not put it at the same place as on the regular form?

did you miss the “as” in the sentence?

2023-03-10 15:49 UTC, victor-champonnois commented on partner_contact_tag/views/res_partner_views.xml
> +                expr="//notebook/page/field[@name='child_ids']/form/sheet//field[@name='mobile']"
Ah maybe ^^

2023-03-10 15:53 UTC, victor-champonnois commented
@carmenbianca I redeployed in test

2023-03-21 10:23 UTC, carmenbianca commented on partner_contact_tag/views/res_partner_views.xml
> +                expr="//notebook/page/field[@name='child_ids']/form/sheet//field[@name='mobile']"
It's technically, visually, in the same spot as on the regular form—in the bottom right.

2023-03-22 08:53 UTC, carmenbianca commented
Implemented fixes suggested by @huguesdk 

Moved to https://github.com/OCA/partner-contact/pull/1489

2023-03-22 08:53 UTC, closed without merging