[16.0][MIG] l10n_be_national_number
coopiteasy/addons pull request #318
Opened 2024-03-25 14:33 UTC by victor-champonnois

l10n_be_national_number was implemented in v14 and published on https://github.com/OCA/l10n-belgium. 
In v16, there is the module https://github.com/OCA/l10n-belgium/tree/16.0/l10n_be_partner_identification that does the same thing with more functionalities.

We need to migrate the data. The module l10n_be_national_number is moved here, and contain a migration script and a dependency to l10n_be_partner_identification. 

internal task
https://gestion.coopiteasy.be/web?debug=1#id=12259&action=479&model=project.task&view_type=form&menu_id=536

2024-03-29 08:22 UTC, huguesdk requested changes

2024-03-29 08:22 UTC, huguesdk commented on l10n_be_national_number/migrations/16.0.2.0.0/pre-migration.py
> +    for id_numbers in env["res.partner"].search([]).mapped("id_numbers"):
```suggestion
    for id_numbers in (
        env["res.partner"]
        .with_context(active_test=False)
        .search([])
        .mapped("id_numbers")
    ):
```
`.with_context(active_test=False)` is needed to also convert id numbers of inactive partners.

2024-03-29 08:22 UTC, huguesdk commented on l10n_be_national_number/migrations/16.0.2.0.0/pre-migration.py
> +            ).id
the `env.ref()` calls should go outside the loop to avoid looking up the symbol at each iteration.

2024-03-29 14:11 UTC, victor-champonnois commented
@huguesdk thanks for the review, PR fixed!

2024-03-29 15:08 UTC, huguesdk requested changes
thanks for fixing the migration script. sorry, i didn’t look close enough into it the first time, so here are more remarks.

2024-03-29 15:08 UTC, huguesdk commented on l10n_be_national_number/migrations/16.0.2.0.0/pre-migration.py
> +            id_numbers.category_id = new_id
actually, i think this won’t work if there are multiple `id_numbers` on a partner, which can be the case as its a one2many relationship. instead, you should work with `res.partner.id_number` records directly. one way is to do it like this:

```suggestion
    old_id = env.ref("l10n_be_national_number.l10n_be_national_number_category").id
    new_id = env.ref(
        "l10n_be_partner_identification.l10n_be_national_registry_number_category"
    ).id
    id_numbers = (
        env["res.partner.id_number"]
        .with_context(active_test=False)
        .search([("category_id", "=", old_id)])
    )
    id_numbers.write({"category_id": new_id})
```

another is like this:

```suggestion
    old_id = env.ref("l10n_be_national_number.l10n_be_national_number_category").id
    new_id = env.ref(
        "l10n_be_partner_identification.l10n_be_national_registry_number_category"
    ).id
    env.cr.execute(
        """
        update res_partner_id_number
        set category_id = %(old_id)s
        where category_id = %(new_id}s
        """,
        {"old_id": old_id, "new_id": new_id},
    )
```

2024-03-29 15:40 UTC, victor-champonnois commented
@huguesdk fixed !

2024-03-29 16:18 UTC, huguesdk approved these changes
👍

2024-04-29 12:16 UTC, victor-champonnois commented
/ocabot merge nobump

2024-04-29 12:49 UTC, polchampion approved these changes
functional check: LGTM

2024-04-30 07:40 UTC, victor-champonnois commented
/ocabot merge nobump

2025-07-31 10:58 UTC, remytms commented
/ocabot merge nobump

2025-07-31 11:06 UTC, merged