[12.0][ADD] resource_multi_week_work_time_from_contracts
coopiteasy/addons pull request #324
Opened 2024-09-03 11:42 UTC by carmenbianca

## Description

A glue module between #323 and https://github.com/OCA/hr/pull/1389

Built on top of #323, depends on https://github.com/OCA/hr/pull/1389

## Odoo task (if applicable)

T12626 and T12627

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

2024-09-04 12:00 UTC, carmenbianca commented on resource_multi_week_work_time_from_contracts/models/resource_calendar.py
> +                    break
the `days_to_monday` computation is only necessary for the first pass; after that it is always 7. move it out of the loop, and put `days_to_monday = 7` at the end of the loop.

`next_monday = date_from` is incorrect at the moment of assignment. we want to avoid that because it's hard to read.

`candidate` should be None if none is found.

2024-09-04 12:00 UTC, carmenbianca commented on resource_multi_week_work_time_from_contracts/models/resource_calendar.py
> +                ).replace(hour=23, minute=59, second=59, microsecond=99999)
`date_to` is a date, not a datetime.

2024-09-04 12:45 UTC, carmenbianca commented
![Capture d’écran du 2024-09-04 14-45-06](https://github.com/user-attachments/assets/03386643-525e-4955-aa69-2c3fb3529e8a)

add a domain here to not be able to select children

2024-09-09 08:34 UTC, huguesdk requested changes
> add a domain here to not be able to select children
> 
> edit: done

where is this done?

2024-09-09 08:34 UTC, huguesdk commented on resource_multi_week_work_time_from_contracts/models/__init__.py
> +from . import resource_calendar
`resource_mixin` should also be imported.

```suggestion
from . import resource_calendar
from . import resource_mixin
```

2024-09-09 12:50 UTC, carmenbianca commented
> > add a domain here to not be able to select children
> > edit: done
> 
> where is this done?

[0202a82](https://github.com/coopiteasy/addons/pull/324/commits/0202a82a9a0397fefe94493d76f7cf2de0ad5af8)

2024-09-09 13:04 UTC, huguesdk commented on resource_multi_week_work_time_from_contracts/views/hr_contract_views.xml
> +                >[('parent_calendar_id', '=', False)]</attribute>
shouldn’t it better to add this domain on the field in the model directly, so that it applies everywhere?

2024-09-10 08:42 UTC, huguesdk approved these changes

2024-10-09 14:21 UTC, huguesdk commented
/ocabot merge nobump

2024-10-09 14:36 UTC, merged