[12.0] [ADD] purchase_supplier_franco
coopiteasy/addons pull request #328
Opened 2024-09-13 09:56 UTC by victor-champonnois

https://gestion.coopiteasy.be/mail/view?model=project.task&res_id=12658

2024-09-13 12:50 UTC, huguesdk requested changes
looks good to me, except for the name of the field and the module. “franco” doesn’t seem to mean anything in english. i would advise to use “free_shipping_threshold”.

moreover, did you take a look at `delivery.carrier.free_over` field in the standard `delivery` module?

2024-09-13 12:59 UTC, victor-champonnois commented
@huguesdk yes good idea to rename free_shipping_threshold. I fixed that.
Yes I know about the delivery module, but it's for delivering to clients, here the threshold is for the delivery costs at reception.

2024-09-13 13:02 UTC, huguesdk requested changes
still one `franco` to replace. 😉 also, to make pre-commit pass, you need to add the `setup/purchase_supplier_free_shipping_threshold` directory.

2024-09-13 13:02 UTC, huguesdk commented on purchase_supplier_free_shipping_threshold/models/purchase_order.py
> +    free_shipping_threshold = fields.Monetary(related="partner_id.franco")
```suggestion
    free_shipping_threshold = fields.Monetary(related="partner_id.free_shipping_threshold")
```

2024-09-13 13:42 UTC, huguesdk approved these changes
all good now!

2024-09-13 13:45 UTC, victor-champonnois commented
@huguesdk a thousand thanks :pray:

2024-09-13 15:00 UTC, victor-champonnois commented
@huguesdk I squashed my commits.

2024-09-24 13:55 UTC, huguesdk commented
/ocabot merge nobump

2024-09-24 14:09 UTC, merged