9.0 mrp brewing fix raw materials
coopiteasy/addons pull request #33
Opened 2019-10-16 16:23 UTC by vvrossem

Raw Material reports include :
- date display according to user timezone
- outputs for customers in addition to production and inventory

2019-10-17 11:56 UTC, houssine78 commented on mrp_brewing/report/report_stock_raw_materials.xml
>                                      <td/>
I don't understand why location of usage customer appear in this report. This is the raw material report. So the report telling what are the stock variation for the raw material product. I don't think we should add customer usage here

2019-10-17 11:56 UTC, houssine78 requested changes
could you please take my comment into account

2019-10-23 08:13 UTC, vvrossem commented
@houssine78 ok to merge ? (cfr. email 17.10.19 - 15:13)

2019-10-24 08:08 UTC, houssine78 approved these changes

2019-10-24 08:09 UTC, houssine78 commented
@vvrossem ok pour moi !

2019-10-24 10:00 UTC, merged