[ADD] document_hosting
coopiteasy/addons pull request #45
Opened 2019-11-18 10:29 UTC by elouan-lb

Previously module `easy_my_coop_document` in `easy_my_coop` repository. See https://github.com/coopiteasy/vertical-cooperative/pull/40

2019-11-19 10:08 UTC, houssine78 commented on document_hosting/__manifest__.py
> +
It's more a generic module now. Document is more accurate

2019-11-19 10:10 UTC, houssine78 commented on document_hosting/__manifest__.py
> +    'author': 'Rémy Taymans',
```suggestion
   "author": "Coop IT Easy SCRLfs",
```

2019-11-19 10:12 UTC, houssine78 commented on document_hosting/__manifest__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
# Copyright 2018-Coop IT Easy SCRLfs (<http://www.coopiteasy.be>)
# - Rémy Taymans <remy@coopiteasy.be>
# - Elouan Le bars <elouan@coopiteasy.be>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).

2019-11-19 10:15 UTC, houssine78 commented on document_hosting/views/document_hosting_menu.xml
> +     License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
```suggestion
# Copyright 2018 - Today Coop IT Easy SCRLfs (<http://www.coopiteasy.be>)
```

2019-11-19 10:16 UTC, houssine78 commented on document_hosting/views/document_hosting_menu.xml
> +     Copyright 2018 Rémy Taymans <remytaymans@gmail.com>
```suggestion
     Copyright 2018 - Today Coop IT Easy SCRLfs (<http://www.coopiteasy.be>)
```

2019-11-19 10:16 UTC, houssine78 requested changes
very small changes

2019-11-20 10:38 UTC, remytms requested changes
This is my Xmas wish list:
- Use `isort` on all python file except `__init__.py` ones.
- Paint code in black with `black -l 79 <module_name>`
- Change copyright holder everywhere as Houssine suggested.

Thanks a lot ! :)

2019-11-20 10:38 UTC, remytms commented on document_hosting/__manifest__.py
> +
Remove this empty line at the beginning of the document. :)

2019-11-20 10:38 UTC, remytms commented on document_hosting/__manifest__.py
> +    Manage the documents of your cooperative.
Suggestion: "Manage documents that can be published on website with `document_hosting_website`."

2019-11-20 10:38 UTC, remytms commented on document_hosting/models/document.py
> +
Remove empty line in the beginning of the document.

2019-11-20 10:38 UTC, remytms commented on document_hosting/models/document.py
> +# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
Change license as Houssine suggested.

2019-11-20 10:38 UTC, remytms commented on document_hosting/models/document.py
> +from odoo import models, fields, api
Can you use `isort` to sort imports on models. :)

2019-11-20 10:38 UTC, remytms commented on document_hosting/views/document_hosting_views.xml
> +-->
Change license as Houssine suggested.

2019-11-20 10:38 UTC, remytms commented on document_hosting/views/document_hosting_views.xml
> +  <data>
Remove `data` tag. Not needed.

2019-11-20 18:05 UTC, elouan-lb commented
Thank you for the review @houssine78 & @remytms ! Changes were made, happy Christmas ! Migration and renaming of `easy_my_coop_website_document` into `document_hosting_website` is still needed.

2019-11-21 08:46 UTC, houssine78 approved these changes

2020-01-10 10:36 UTC, remytms approved these changes

2020-01-16 13:16 UTC, elouan-lb commented
Added `easy_my_coop_website_document` as well. Documents display is configurable. See https://github.com/coopiteasy/vertical-cooperative/pull/58

2020-02-06 12:00 UTC, houssine78 commented on document_hosting/__manifest__.py
> +    "website": "https://github.com/coopiteasy/addons",
best to put www.coopiteasy.be instead

2020-02-06 12:01 UTC, houssine78 approved these changes

2020-02-10 14:09 UTC, elouan-lb commented on document_hosting/__manifest__.py
> +    "website": "https://github.com/coopiteasy/addons",
Done !

2020-02-10 14:41 UTC, merged