[9.0][ADD] provelo_customization: hr_holidays leaves record rules
coopiteasy/addons pull request #64
Opened 2020-03-09 13:12 UTC by vvrossem

**Before**
- an _Employee_ could see other employees' leaves

**After**
- an _Employee_ can only see its own leaves
- a _Department Manager_ can only see both its employees' leaves and own leaves
- a _HR Manager_ can see all leaves

Thanks @robinkeunen for the help !

2020-03-09 16:03 UTC, vvrossem commented
@robinkeunen validé par Cath, ok pour toi ?

2020-03-09 18:01 UTC, robinkeunen requested changes
See my comments. Welcome to the club of the rulers.

2020-03-09 18:01 UTC, robinkeunen commented on provelo_customization/security/security.xml
> +            <field name="groups" eval="[(4, ref('base.group_hr_user'))]"/>
`group_hr_user` est le _Officer_, c'est bien à lui et pas à `group_hr_manager` que tu veux filer tous les droits?

2020-03-09 18:01 UTC, robinkeunen commented on provelo_customization/security/security.xml
> +            <field name="groups" eval="[(4, ref('base.group_hr_user'))]"/>
Same comment here.

2020-03-10 08:54 UTC, vvrossem commented on provelo_customization/security/security.xml
> +            <field name="groups" eval="[(4, ref('base.group_hr_user'))]"/>
En fait, ce groupe était déjà utilisé lorsque j'ai dupliqué les `rules` sur `hr_holidays`.
Quid si l'on change les `group_user` en `group_hr_user` et les `group_hr_user` en `group_hr_manager` ?

2020-03-10 10:22 UTC, vvrossem commented
@robinkeunen FYI I changed `group_user` to `group_hr_user` and `group_hr_user` to `group_hr_manager` both for `account_analytic_lines` and `hr_holidays`. I tested locally and it works fine. Catherine is going to test on the client's instance.

2020-03-10 10:28 UTC, robinkeunen commented on provelo_customization/security/security.xml
> +            <field name="groups" eval="[(4, ref('base.group_hr_user'))]"/>
- `group_user`, ce sont les employés, à laisser,
- `group_hr_user`, ce sont les employés de la RH,
- `group_hr_manager`, ce sont les managers de la RH.

Du coup, en reformulant, je pense que tes règles sont fonctionnellement correctes. Juste renommer `hr_manager_all_account_analytic_line` en `hr_officer_all_account_analytic_line` pour la cohérence et clarté.

2020-03-10 10:29 UTC, robinkeunen commented
> @robinkeunen FYI I changed `group_user` to `group_hr_user` and `group_hr_user` to `group_hr_manager` both for `account_analytic_lines` and `hr_holidays`. I tested locally and it works fine. Catherine is going to test on the client's instance.

Ha mert, cf my comment in the code.

2020-03-10 11:49 UTC, vvrossem commented on provelo_customization/security/security.xml
> +            <field name="groups" eval="[(4, ref('base.group_hr_user'))]"/>
Merci pour ces éclaircissements !

2020-03-10 11:49 UTC, vvrossem commented
Rollback et renommé hr_manager en hr_officer :)

2020-03-11 12:23 UTC, merged