[12.0] [MIG] purchase_order_weight
coopiteasy/addons pull request #78
Opened 2020-04-09 16:25 UTC by vvrossem

### [Task](https://gestion.coopiteasy.be/web#id=3150&view_type=form&model=project.task&action=475&active_id=98)

### Behavior
> Adds weight and weight unit to Purchase Order

### Screenshots
#### `display_weight` and `display_unit`
These fields appear but are not editable as they are `related` fields therefore read only by default.
![purchase_order_weight1](https://user-images.githubusercontent.com/28013700/78917385-189bd800-7a8f-11ea-88d2-02461e516f5a.png)

#### Request for quotation (pdf)
![purchase_order_weight2](https://user-images.githubusercontent.com/28013700/78917399-1afe3200-7a8f-11ea-9e99-0b0e67d8c0d2.png)

#### Purchase order confirmation (pdf)
![purchase_order_weight3](https://user-images.githubusercontent.com/28013700/78917412-1d608c00-7a8f-11ea-8f60-0a4a0703865c.png)

2020-04-10 13:05 UTC, robinkeunen requested changes
Yo,

Good stuff, but I think it'd be better to remove the dependency on `beesdoo_product.`

A little black on this module would be nice as well.

2020-04-10 13:05 UTC, robinkeunen commented on purchase_order_weight/__init__.py
> +from . import models
missing EOL

2020-04-10 13:05 UTC, robinkeunen commented on purchase_order_weight/__manifest__.py
> +    "author": "Coop IT Easy - Robin Keunen <robin@coopiteasy.be>",
Coop IT Easy SCRLfs

2020-04-14 08:35 UTC, vvrossem commented on purchase_order_weight/__init__.py
> +from . import models
done :)

2020-04-14 08:35 UTC, vvrossem commented on purchase_order_weight/__manifest__.py
> +    "author": "Coop IT Easy - Robin Keunen <robin@coopiteasy.be>",
done :)

2020-04-14 08:35 UTC, vvrossem commented
@robinkeunen thanks for the fixup! training

2020-04-30 14:33 UTC, vvrossem commented
@robinkeunen ok to merge?

2020-04-30 15:27 UTC, robinkeunen approved these changes

2020-04-30 15:27 UTC, robinkeunen commented
@vvrossem yay

2020-05-05 16:57 UTC, merged